import { defineStore } from 'pinia'

export const useEducation = defineStore('education', {
    state: () => ({
        station: [
            {
                img: 'education/leon.png',
                sprite: 'sprite/leon.png',
                name: '里昂·S·甘乃迪',
                position: '學校警衛',
                description: '校園警衛里昂，會用 BB 彈處理不守規矩的學生。嚴禁讓警衛駕駛任何載具，如發生事故後果將由其高額工資承擔。若發生喪屍入侵，請通知警衛：假期結束，請回來上班。',
                origin: '惡靈古堡系列',
                painter: 'TSUJI',
                painterURL: '',
                index: 0,
            },
             {
                img: 'education/felyne.png',
                sprite: 'sprite/felyne.png',
                name: '艾露貓奶奶',
                position: '營養午餐奶奶',
                description: '喵~喵喵~(要吃飽喔！(⁠=⁠^⁠･⁠~･⁠^⁠=⁠))能煮出非常好吃營養午餐的奶奶，身後都會跟著幾隻小艾露貓幫忙一起拿餐桶，因為營養午餐超好吃會引起附近學校的羨慕忌妒恨。',
                origin: '魔物獵人系列',
                painter: '毛帽',
                painterURL: '',
                index: 1,
            }, {
                img: 'education/luke.png',
                sprite: 'sprite/luke.png',
                name: '盧克·蘇利文',
                position: '綜合格鬥社指導老師',
                description: '蘇利文老師每次社團課都滿腔熱血，一副精力過剩的樣子，從未見他露出疲態。軍職出身卻不死板，是平易近人且關心學生的超大型黃金獵犬型男老師！「今天也要加油呢！盡情切磋，不要忘記熱身嘍！」如果太累想翹掉社課，老師大概也會睜一隻眼閉一隻眼的......！',
                origin: '快打炫風系列',
                painter: '阿祈',
                painterURL: '',
                index: 2,
            }, {
                img: 'education/hikari.png',
                sprite: 'sprite/netto.png',
                name: '光熱斗&洛克人.exe',
                position: '電腦老師',
                description: '偶然來學園兼職的電腦老師光熱斗跟他的網路領航員洛克人.exe。即便成為老師仍然天天遲到，今天也會活力十足的教大家使用網路對戰清除病毒！',
                origin: '洛克人EXE系列',
                painter: '魚翅',
                painterURL: '',
                index: 3,
            }, {
                img: 'education/vergil.png',
                sprite: 'sprite/vergil.png',
                name: '維吉爾',
                position: '國文老師',
                description: '明明志願是英文老師，卻不知為何被安排到了國文老師的職位。「維吉爾先生喜歡詩詞對吧，那教授國文肯定不在話下！」就這樣，雖不情願但更不願示弱的維吉爾接下了這份職責。上課時討厭一切噪音，而他腰間那把從不離身的武士刀，似乎不是單純的裝飾……！',
                origin: '惡魔獵人系列',
                painter: '阿綠',
                painterURL: '',
                index: 4,
            }, {
                img: 'education/dante.png',
                sprite: 'sprite/dante.png',
                name: '但丁',
                position: '音樂老師',
                description: `這屆的音樂老師不唱搖籃曲，尖銳的電吉他刺破古典音符，讓但丁來教你什麼是party 吧！"This party's getting crazy. Let's rock!" Ps:請注意音量，否則會有個和但丁長相一樣的國文老師憑空出現`,
                origin: '惡魔獵人系列',
                painter: '蘇朵',
                painterURL: '',
                index: 5,
            }, {
                img: 'education/nero.png',
                sprite: 'sprite/nero.png',
                name: '尼祿',
                position: '家政老師',
                description: '自學各種縫紉與烹飪技巧的家政老師尼祿，似乎和某兩位老師有血緣上的淵源。雖然身為老師，但總是會不小心說粗話。即便一邊的手是機械，縫紉是完全沒問題的。鍋鏟偶爾會在老師手上斷掉，也許是品質不夠好吧！',
                origin: '惡魔獵人系列',
                painter: '米若',
                painterURL: '',
                index: 6,
            }, {
                img: 'education/naruhodo.png',
                sprite: 'sprite/naruhodo.png',
                name: '成步堂龍一',
                position: '戲劇社老師',
                description: '成步堂萬事通事務所所長，為本校法律顧問兼任戲劇社指導老師。作為司法界的傳奇不敗律師，據說是藝術系戲劇組畢業的!?老師的心法，就是無論在法庭或是舞台上，最重要的是保持虛張聲勢的氣勢和屹立不搖的決心！唯一困擾的是，老師喊卡的時候會不小心大喊「異議あり！」，常常嚇到社員。',                
                origin: '逆轉裁判系列',
                painter: '小雪',
                painterURL: '',
                index: 7,
            }, {
                img: 'education/mitsurugi.png',
                sprite: 'sprite/mitsurugi.png',
                name: '御劍憐侍',
                position: '辯論社客座',
                description: '被戲劇社老師請來當辯論社客座。對於自己的想法總是很堅持、時常把學生瞪哭，但對於關心的人私底下很暖心。興趣是下西洋棋，偶爾會跟國文老師對弈。口頭禪是:下個月的社團分數等著瞧',                
                origin: '逆轉檢事系列',
                painter: '米若',
                painterURL: '',
                index: 8,
            },{
                img: 'education/odoroki.png',
                sprite: 'sprite/odoroki.png',
                name: '王泥喜法介',
                position: '魔術社指導教師',
                description: '憑藉著在成步堂萬事通事務所間接習得的魔術技法，在魔術社擔任指導教師。不知為何魔術道具中總會混雜著打掃用品，看來老師也很擅長整理清潔呢。王泥喜法介！今天也沒有問題！',                
                origin: '逆轉裁判系列',
                painter: '阿柚',
                painterURL: '',
                index: 9,
            },{
                img: 'education/naruhodo_ancient.png',
                sprite: 'sprite/naruhodo_ancient.png',
                name: '成步堂龍之介',
                position: '保健室老師',
                description: '主修英文，勇盟大學現役大學生。很有禮貌，但有點冒失。似乎總是在吃東西。因為幾乎不會生病所以被叫來當保健室老師。難道護理師證書跟律師證一樣是可以借來借去的嗎……？太糾結這種細節可是沒辦法玩逆轉裁判的！',
                origin: '大逆轉裁判系列',
                painter: '眼蟲',
                painterURL: '',
                index: 10,
            },
            
        ],
        navlink: [
            {
                title: '比賽章程',
                link:'#theme'
            },
        ],
        date: [
          {
            txt:{
                date: '1/08 - ',
                start: '敬請期待',
                goon: '比賽公布',
                end: '比賽資訊公布',
            },
            start: Date.parse('08 Jan 2024 00:00:00'),
            end: Date.parse('09 Jan 2024 12:30:00'),
            url: '/picnic2',
          },
        ],
        member: [
          {
            title:'拍立得獎',
            luckysquid: '檸朦、帽子',
            image: 'prize/picnic-b/2A.jpg',
          },
        ]
    })
})